name: Pack H5P Content Type H5P-Music-Notation

on: 
  push:
    branches: [main]

jobs:
  pack:
    name: Pack with H5P-Music-Notation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install npm 
        run: npm ci
      - name: run h5p pack
        run: |
          npm install -g h5p
          cd ..
          h5p pack H5P-MusicNotation H5P-MusicNotation/package/h5p-musicnotation.h5p
